#!/bin/bash
cat './dynabook/Cuis5.0-4526.image' | gzip | tee './dynabook/Cuis5.0-4526.image.gz' > /dev/null
git add ./dynabook/*.sources
git add './dynabook/Cuis5.0-4526.image.gz' './dynabook/Cuis5.0-4526.changes' ./dynabook/*.sources addImageAndChanges $@
